### PR TITLE
fix ignore cue id, fix some style

### PR DESCRIPTION
**Pull request by kocoten1992**
1789
02:16:52.119 --> 02:16:54.204
I'm guilty of committing a crime.

1790
02:16:55.873 --> 02:16:57.957
Parole violation.

1789, 1790 are cue id, remove and ignore cue id

### CODE REVIEW

**Comment by kocoten1992** [comment]
@mantas-done , could these keyword allowed to have underline, those red X make me nervous
```php
    __FILE__      // The full path and filename of the file.
    __DIR__       // The directory of the file.
    __FUNCTION__  // The function name.
    __CLASS__     // The class name.
    __METHOD__    // The class method name.
    __LINE__      // The current line number of the file.
    __NAMESPACE__ // The name of the current namespace
```

**Comment by mantas-done** [comment]
1789
02:16:52.119 --> 02:16:54.204
I'm guilty of committing a crime.

1790
02:16:55.873 --> 02:16:57.957
Parole violation.

Hi, these seems like .srt file (not .vtt)?

**Comment by kocoten1992** [comment]
https://www.w3.org/TR/webvtt1/#webvtt-cue-identifier

These are optional webvtt-cue-identifier, but I didn't read the spec on this one, sorry

Usually, those optional web cue identifier are number, but seem like any word not containing ```-->``` can be too, I'll update code this

**Comment by mantas-done** [comment]
Also please add example of the file that is causing you the problem, I will add it to the test. Or if you want, you can add it :)

**Comment by kocoten1992** [comment]
To clarify, those id usually come when ppl convert srt to vtt, some converter don't throw off these id

**Comment by kocoten1992** [comment]
[the.shawshank.redemption.1994.txt](https://github.com/mantas-done/subtitles/files/1387897/the.shawshank.redemption.1994.txt)

Github don't support vtt file, change txt to vtt when download, thank you.

**Comment by mantas-done** [comment]
Sorry for the late reply.
I have renamed your file to .vtt and tried to convert it to .srt with this PHP converter
and with online converter https://gotranscript.com/subtitle-converter

Output of both (.srt) file is exactly the same. I  think I need a bit of your help understanding what problem this commit fixes. Can you explain me. Thanks :)

**Pull request merged**
